[book]
authors = ["Ari <ari@herringbank.com>"]
language = "en"
multilingual = false
src = "src"
title = "Herringbank Development"

[server]
port = 8989

[preprocessor.index]

[preprocessor.links]

[output.html]
